version: '3.9'

services:
  api-gateway:
    container_name: skeleton-microservices-api-gateway
    build: ./api-gateway
    command: npm run start:launcher
    ports:
      - "3000:3000"
    volumes:
      - ./api-gateway/src:/usr/src/app/src
    networks:
      - skeleton-microservices

  microservice-auth:
    container_name: skeleton-microservices-auth
    build: ./microservice-auth
    command: npm run start:launcher
    depends_on:
      - postgres
    volumes:
      - ./microservice-auth/src:/usr/src/app/src
    networks:
      - skeleton-microservices

  microservice-users:
    container_name: skeleton-microservices-users
    build: ./microservice-users
    command: npm run start:launcher
    volumes:
      - ./microservice-users/src:/usr/src/app/src
    networks:
      - skeleton-microservices

  postgres:
    container_name: skeleton-microservices-postgres
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - ./artifacts/postgres:/var/lib/postgresql/data/
    networks:
      - skeleton-microservices
  # pgadmin:
  #   container_name: skeleton-microservices-pgadmin
  #   image: "dpage/pgadmin4"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
  #     PGADMIN_DEFAULT_PASSWORD: 'admin'
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - skeleton-microservices

networks:
  skeleton-microservices:
